---
name: sample-app-benjamin

instance_groups:
  - name: sample-app
    instances: 3
    azs: [ z1 ]
    jobs:
      - name: sample-app
        release: sample-app-benjamin
        provides:
          sample-app: { as: sample-app-benjamin, shared: true }
        properties: {}
      - name: bpm
        release: bpm
    stemcell: default
    vm_type: default
    networks:
      - name: default

update:
  serial: true # instance groups to be deployed sequentially.

  canaries: 1
  canary_watch_time: 1000-5000

  max_in_flight: 1
  update_watch_time: 1000-5000

releases:
  - name: sample-app-benjamin
    version: latest
  - name: bpm
    version: "0.2.0"
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.2.0
    sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest
