---
name: sample-app-benjamin

instance_groups:
  - name: sample-app
    instances: 3
    azs: [ z1 ]
    jobs:
      - name: sample-app
        release: sample-app-benjamin
        provides:
          sample-app: { as: sample-app-benjamin, shared: true }
        properties: {}
      - name: bpm
        release: bpm
    stemcell: default
    vm_type: default
    networks:
      - name: default

update:
  serial: true # instance groups to be deployed sequentially.

  canaries: 1
  canary_watch_time: 1000-5000

  max_in_flight: 1
  update_watch_time: 1000-5000

releases:
  - name: sample-app-benjamin
    version: latest
  - name: "bpm"
    version: "1.1.15"
    url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.15"
    sha1: "0d48aa01a65b947b97570234eb2401e821a8bd35"

stemcells:
  - alias: default
    os: ubuntu-bionic
    version: latest
